[torizon]
url = "https://dgw.torizon.io/ras/"
server_cert_path = "/etc/sota/root.crt"
client_cert_path = "/var/sota/import/client.pem"
client_key_path = "/var/sota/import/pkey.pem"

[device]
# If this file does not exist, a new key will be generated and saved to this file
ssh_private_key_path = "/home/phobos/run/rac/device-key-01.sec"
unprivileged_user_group = "phobos:phobos"
local_tuf_repo_path = "/home/phobos/run/rac/uptane-repo"
poll_timeout = { secs = 30, nanos = 0 }
validation_poll_timeout = { secs = 30, nanos = 0 }
enable_dbus_client = false

[device.session.spawned_sshd]
sshd_path = "/usr/sbin/sshd"
config_dir = "/home/phobos/run/rac"
